---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwks-retriever
spec:
  selector:
    matchLabels:
      app: jwks-retriever
  template:
    metadata:
      labels:
        app: jwks-retriever
    spec:
      containers:
      - name: jwks-retriever
        image: jwks-retriever:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: spiffe-config
        env:
          - name: JWKS_PATH
            value: /run/spire/bundle/jwks.json
        volumeMounts:
          - name: spire-agent-socket
            mountPath: /spire-agent-socket
            readOnly: true
          - name: jwks-dir
            mountPath: /run/spire/bundle
            readOnly: false
      volumes:
        - name: spire-agent-socket
          csi:
            driver: csi.spiffe.io
            readOnly: true
        - name: jwks-dir
          emptyDir:
            medium: Memory
