---
name: Linting - YAML
on:
  push:
    branches: [main]
    paths:
      - "**.yml"
      - "**.yaml"
  pull_request:
    branches: [main]
    paths:
      - "**.yml"
      - "**.yaml"

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
