---
name: Linting - Bash/Bats
on:
  push:
    branches: [main]
    paths:
      - "**.bash"
      - "**.bats"
      - "**.sh"
  pull_request:
    branches: [main]
    paths:
      - "**.bash"
      - "**.bats"
      - "**.sh"

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extention: ["bash", "bats", "sh"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Run shellcheck
        uses: reviewdog/action-shellcheck@v1.12
        with:
          pattern: "*.${{ matrix.extention }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
