---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: aws-cli
  name: aws-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      annotations:
      labels:
        app: aws-cli
    spec:
      serviceAccountName: aws-cli
      containers:
      - image: jwt-fetch:latest
        imagePullPolicy: IfNotPresent
        name: spiffe-jwt
        volumeMounts:
        - name: svid
          mountPath: /svid
          readOnly: false
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spire-agent-socket/socket
      - image: amazon/aws-cli
        name: aws-cli
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: svid
          mountPath: /svid
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spire-agent-socket/socket
      volumes:
      - name: svid
        emptyDir: {}
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
