---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: watcher
  name: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      annotations:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher
      containers:
      - image: ${WATCHER_IMAGE_TAG}
        name: watcher
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spire-agent-socket/socket
      volumes:
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true