apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: example-workloads
spec:
  spiffeIDTemplate: "spiffe://${spire_trust_domain}/{{ .PodSpec.ServiceAccountName }}"
  namespaceSelector:
    matchLabels:
      example: "true"
